#### Model Traning

Importing the requires Libraries:

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, classification_report, precision_score, recall_score
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline




#### Importing the data set

In [2]:
df = pd.read_csv("data/Fake Bills.csv",sep=";")

In [3]:
df.head()

is_genuine  diagonal  height_left  height_right  margin_low  margin_up  \
0        True    171.81       104.86        104.95        4.52       2.89   
1        True    171.46       103.36        103.66        3.77       2.99   
2        True    172.69       104.48        103.50        4.40       2.94   
3        True    171.36       103.91        103.94        3.62       3.01   
4        True    171.73       104.28        103.46        4.04       3.48   

   length  
0  112.83  
1  113.09  
2  113.16  
3  113.51  
4  112.54

In [4]:
X = df.drop(columns='is_genuine')

In [5]:
X.head()

diagonal  height_left  height_right  margin_low  margin_up  length
0    171.81       104.86        104.95        4.52       2.89  112.83
1    171.46       103.36        103.66        3.77       2.99  113.09
2    172.69       104.48        103.50        4.40       2.94  113.16
3    171.36       103.91        103.94        3.62       3.01  113.51
4    171.73       104.28        103.46        4.04       3.48  112.54

In [6]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df['is_genuine']= label_encoder.fit_transform(df['is_genuine'])
  
df['is_genuine'].unique()

array([1, 0], dtype=int64)

In [7]:
y=df['is_genuine']
print(y)

0       1
1       1
2       1
3       1
4       1
       ..
1495    0
1496    0
1497    0
1498    0
1499    0
Name: is_genuine, Length: 1500, dtype: int64


In [8]:

transformer = ColumnTransformer(transformers=[
('imputer',SimpleImputer(strategy='most_frequent'),['margin_low'])],remainder='passthrough')
    


In [9]:
X = transformer.fit_transform(X)

In [10]:
X

array([[  4.52, 171.81, 104.86, 104.95,   2.89, 112.83],
       [  3.77, 171.46, 103.36, 103.66,   2.99, 113.09],
       [  4.4 , 172.69, 104.48, 103.5 ,   2.94, 113.16],
       ...,
       [  5.51, 171.8 , 104.01, 104.12,   3.36, 111.95],
       [  5.17, 172.06, 104.28, 104.06,   3.46, 112.25],
       [  4.63, 171.47, 104.15, 103.82,   3.37, 112.07]])

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)


In [12]:
print("X shape",X_train.shape,X_test.shape)
print("y shape",y_train.shape,y_test.shape)

X shape (1200, 6) (300, 6)
y shape (1200,) (300,)


In [13]:
models = [("logistic regressionn" , LogisticRegression()),
          ("KNN classifier" , KNeighborsClassifier()),
          ("Decesion tree classifier" , DecisionTreeClassifier()),
          ("Random classifier" , RandomForestClassifier()),
          ("Ada boost classifier" , AdaBoostClassifier()),
          ("gradient boosting classifier" , GradientBoostingClassifier()),
]


In [14]:
for name, model in models:
    print(f"Training model: {name}")
    model.fit(X_train, y_train)
    

# Make predictions and evaluate each model using confusion matrices
for name, model in models:
    print(f"Evaluating model: {name}")
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    print(f"Confusion matrix:\n{cm}")
    report = classification_report(y_test, y_pred)
    print(f"Classification report:\n{report}")




Training model: logistic regressionn
Training model: KNN classifier
Training model: Decesion tree classifier
Training model: Random classifier
Training model: Ada boost classifier
Training model: gradient boosting classifier
Evaluating model: logistic regressionn
Confusion matrix:
[[107   3]
 [  0 190]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       110
           1       0.98      1.00      0.99       190

    accuracy                           0.99       300
   macro avg       0.99      0.99      0.99       300
weighted avg       0.99      0.99      0.99       300

Evaluating model: KNN classifier
Confusion matrix:
[[106   4]
 [  0 190]]
Classification report:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       110
           1       0.98      1.00      0.99       190

    accuracy                           0.99       300
   macro avg       0.99      0